### ISSUE TITLE
Japanese translation missing "created by" string

### ISSUE THREAD

**Issue by thomaspark** [thomaspark/flexboxfroggy#101]
Just spotted this missing Japanese string while working on the language menu:
https://github.com/thomaspark/flexboxfroggy/blob/gh-pages/js/messages.js#L75

@ginpei, would you be able to add it?

**Comment by ginpei** [comment]
I could translate but left it in English because the phrase is usually written in English in Japanese culture. I'm sure that most Japanese understand it and feel comfortable.

But do you want me to add a comment there to make it clear?

**Comment by thomaspark** [comment]
Ah, thanks for the explanation, I had no idea. We can leave it as is then!
