### ISSUE TITLE
Play more than once?

### ISSUE THREAD

**Issue by rifuso** [thomaspark/flexboxfroggy#102]
Is there a way to play this game more than once? Reloading and clearing out the storage doesn't seem to make a difference. Every level is always already completed.

**Comment by thomaspark** [comment]
Sure, you can hit the reset link here to clear everything out:

<img width="246" alt="screen shot 2017-04-09 at 5 43 11 pm" src="https://cloud.githubusercontent.com/assets/900407/24841193/0f2d4914-1d4c-11e7-98ce-2e5ce19a6d23.png">

**Comment by rifuso** [comment]
Oh cool. I totally missed that! Haha

Thanks
