### ISSUE TITLE
[Suggestion] Auto apply styles

### ISSUE THREAD

**Issue by RubenSandwich** [thomaspark/flexboxfroggy#11]
Instead of having to press submit every time to apply the styles and check your work. It would be beneficial if the styles auto applied allowing the learner to see their work without having to submit.

**Comment by thomaspark** [comment]
I like the idea of auto applying styles. But I'm wondering what the role of the submit button should be then.

For example, you type in the correct solution and the frog is on the lilypad. At that point, should the answer be checked automatically, or require a button click?

If checked automatically, I could see it rushing the user onto the next level before they get a chance to see and internalize the problem/solution. But it might also feel redundant and pointless to require a button click after the frog is already on the lilypad.

**Comment by tommarshall** [comment]
Agree that auto applying the styles would be a nice addition. It would encourage playing with different values in the earlier levels where the values are listed.

If you went to auto applied styles then it might make sense to change the submit button to a next button, disabled by default, that becomes visibly enabled when you have the right answer?

**Comment by ralts00** [comment]
send the result to the ENTER key . : D

**Comment by thomaspark** [comment]
I like @tommarshall's idea for changing it to the "next" button. Gonna get to work on this...
