### ISSUE TITLE
Error on load page

### ISSUE THREAD

**Issue by LittaPanda** [thomaspark/flexboxfroggy#111]
There is an error when loading page.
Seems to be happening only on Chrome and recently (about a week ago).
```
Uncaught ReferenceError: Parse is not defined
    at game.js:1
```
```
Parse.initialize("FwVMmzHookZZ5j9F9ILc2E5MT5ufabuV7hCXKSeu");
```
Browser: Chrome Version 60.0.3112.78 (Official Build) (64-bit)
OS: macOs Sierra 10.12.4

**Comment by thomaspark** [comment]
@LittaPanda, thanks for the bug report. Does it happen when you run Froggy in incognito mode? How about if you clear browser data for flexboxfroggy.com?

**Comment by LittaPanda** [comment]
It happens even if I try a hard reload from dev mode.

**Comment by LittaPanda** [comment]
My bad. In incognito mode it does work.
I've tried clearing the entire cache of my browser, I've also manually cleared the cache data and local storage data for the page, but it still happens.
What could be happening here?
Cheers.

**Comment by thomaspark** [comment]
Any reason the Parse script at https://unpkg.com/parse@1.9.2/dist/parse.min.js might not be loading? Maybe a browser extension is blocking it?
