### ISSUE TITLE
Make `<div class="line-numbers">` fill the container height

### ISSUE THREAD

**Issue by Repjarms** [thomaspark/flexboxfroggy#112]
When looking at the container for code, there seems to be a hairline gap at the bottom of the code lines. Adding `height: 100%` to the `.line-numbers` class seems to fix this.

I wanted to post this here in the event that it was helpful. Happy to make a PR if desired.

Without `height: 100%`:
![image](https://user-images.githubusercontent.com/4694018/28731555-64183888-73a2-11e7-9526-6f86cea5bd6e.png)

With `height: 100%`:
![image](https://user-images.githubusercontent.com/4694018/28731581-7ef6a82e-73a2-11e7-98f9-28903e812f6f.png)

**Comment by thomaspark** [comment]
Hey @Repjarms, looks like that gap shows up due to rounding error. Would love a PR on this!
