### ISSUE TITLE
Input Box align is not proper

### ISSUE THREAD

**Issue by ankit2670** [thomaspark/flexboxfroggy#118]
![image](https://user-images.githubusercontent.com/19245567/32102458-0b253764-bb3a-11e7-849f-ffc50940a50a.png)

**Comment by thomaspark** [comment]
Can't replicate this on Firefox 56 on Mac. Could you try disabling your add-ons and see if it's still a problem?

**Comment by ankit2670** [comment]
yeah, I figured it out. They were due to the addons.

**Comment by thomaspark** [comment]
Thanks.

**Comment by ankit2670** [comment]
welcome
