### ISSUE TITLE
Levels 19 & 20 have multiple solutions

### ISSUE THREAD

**Issue by veltman** [thomaspark/flexboxfroggy#12]
For level 19 & 20, using `flex-direction: column;` or `flex-direction: column-reverse;` has the same effect in terms of frog-lilypad color matches, but only the former is accepted as a correct answer.

**Comment by thomaspark** [comment]
Thanks for the bug report. Both answers should result in identical layouts, but the positions seems to be off by a few hundredths of a pixel. Fix on the way.

**Comment by veltman** [comment]
Awesome! It's a great game, thanks for making it.

**Comment by wegosi** [comment]
also for level 19
flex-wrap: wrap;
flex-direction: column-reverse;
