### ISSUE TITLE
Labeled Level

### ISSUE THREAD

**Issue by joseglego** [thomaspark/flexboxfroggy#147]
This is not an issue. It's more like a suggestion.

Have you thought in show the level with a little label, at least with a hover or tooltip, but I think as a labeled list should be better.

In this way. The game would not be only to learn it'd be useful as reference when you want to check something in special or want to re-check something which already achieved.

**Comment by thomaspark** [comment]
Hey @joseglego, tooltips are added to the version on [codepip.com](https://codepip.com) but I'll add it to this one as well.

**Comment by thomaspark** [comment]
Adding now. I'll also consider alternate designs for the level menu that make it more obvious.
