### ISSUE TITLE
Level 15 mentions a Red frog, but only green frogs are visible

### ISSUE THREAD

**Issue by sanderobdeijn** [thomaspark/flexboxfroggy#156]
Level 15 shows only 4 green frogs and 4 green lily pads

**Comment by thomaspark** [comment]
Hi @sanderobdeijn, thanks for the report. There should be 3 green and 1 red on that level. Can you take a screenshot and give your browser info?

**Comment by lkreimann** [comment]
I'm on Firefox 72.0.1 (64-bit) and I can see 4 green frogs and 1 red frog and their lily pads: 
![image](https://user-images.githubusercontent.com/22977266/73092283-9a428780-3edc-11ea-9c0d-82b927de22a2.png)

**Comment by thomaspark** [comment]
Thanks for confirming @lkreimann, I'll close this issue until someone else can replicate it.
