### ISSUE TITLE
Fix translation on frontpage

### ISSUE THREAD

**Issue by sanmai-NL** [thomaspark/flexboxfroggy#160]
I can't trace back the text on https://flexboxfroggy.com/#nl to this repo. It contains a grammatical error which I'd like to fix.

**Comment by thomaspark** [comment]
Hey @sanmai-NL, it's broken up into these 3 files:

* [levels.js](https://github.com/thomaspark/flexboxfroggy/blob/gh-pages/js/levels.js) - instructions text
* [docs.js](https://github.com/thomaspark/flexboxfroggy/blob/gh-pages/js/docs.js) - tooltips text
* [messages.js](https://github.com/thomaspark/flexboxfroggy/blob/gh-pages/js/messages.js) - UI text
