### ISSUE TITLE
typo 'hoppy'

### ISSUE THREAD

**Issue by delusionxb** [thomaspark/flexboxfroggy#167]
```Just look how hoppy they are!``` after beat all 24 courses.

**Comment by systimotic** [comment]
Hi @delusionxb!

I believe this is intended. The frogs on the right are "hopping" (jumping).
The next line also has a similar pun "If you found this ribbeting," Ribbeting is the sound frogs make, "riveting" is the word that is being referred to.

**Comment by delusionxb** [comment]
O...K..., this is an acceptable explanation.
