### ISSUE TITLE
[suggestion] Joining Hacktoberfest!

### ISSUE THREAD

**Issue by omriattiya** [thomaspark/flexboxfroggy#190]
Have you heard about [Hacktoberfest](https://hacktoberfest.digitalocean.com/)? I think that this will give opportunity to a lots of contributors to help this repo (maybe translate froggy to every language!)

**Comment by thomaspark** [comment]
Hey @omriattiya, I think it's a great idea, would love more languages, especially to bring Garden to parity with Froggy. But we'll have to unjoin if it invites spam. I'll add the Flexbox Froggy and Grid Garden repos and see how it goes.

**Comment by omriattiya** [comment]
Good luck 👍
