### ISSUE TITLE
Level 20 English is not in the correct language.

### ISSUE THREAD

**Issue by LukeJansen** [thomaspark/flexboxfroggy#199]
![image](https://user-images.githubusercontent.com/5721434/95845562-3dc11a00-0d42-11eb-98ad-883e49ad81aa.png)

Level 20 is set to english but is not in English!

**Comment by LukeJansen** [comment]
![image](https://user-images.githubusercontent.com/5721434/95846844-d7d59200-0d43-11eb-97cc-d55849d8a400.png)


Just to add that the level win screen has the same problem.

**Comment by minna-xD** [comment]
That's Estonian (et)

**Comment by LukeJansen** [comment]
> That's Estonian (et)

Oh ok! However, it is showing up when I have English selected which is the issue.

**Comment by minna-xD** [comment]
That's apparently because Estonian has accidentally en language code in those two cases and it's picked up. Anyone can fix it but maybe Estonian translator wants to..? @sten9911

**Comment by minna-xD** [comment]
Also the other two js files should be checked. Found the same mistake in docs.js.

**Comment by LukeJansen** [comment]
Ahh that makes sense I am just a user and haven't contributed before so I will leave it up to the translator!

**Comment by ceriwestcott** [comment]
Just found this website, same issue. I could figure out what to do but yeah, it was a pain.

**Comment by thomaspark** [comment]
Thanks for the bug report guys. Fix is on the way.

**Comment by thomaspark** [comment]
It should be fixed. Reload your browser and it should display correctly now.
