### ISSUE TITLE
Visual feedback  validating last lvl (24)

### ISSUE THREAD

**Issue by chikamichi** [thomaspark/flexboxfroggy#2]
Hi,

Congratulations for this excellent project :gift: 

I made it to the last lvl, 24 of 24, but didn't notice the validation message ("You win! Thanks to your mastery of flexbox, you were able to bring all of the frogs to safety.") for I was focused on the frogs themselves, in the right pane.

It could be nice adding a little completion animation when the game is over.

**Comment by thomaspark** [comment]
Thanks @chikamichi, great idea. Right now it's not obvious (let alone satisfying) that you've won the game, and you even miss out on the "fly out" animation of every other level. Gonna add something shortly.

**Comment by thomaspark** [comment]
Here's a screenshot of the new end screen:

<img width="1073" alt="screen shot 2015-11-25 at 4 09 03 pm" src="https://cloud.githubusercontent.com/assets/900407/11409571/e3af7476-938e-11e5-9ad8-83ba1020da74.png">

**Comment by chikamichi** [comment]
Excellent :)
