### ISSUE TITLE
How can I reset all of my solutions?

### ISSUE THREAD

**Issue by obadakhalili** [thomaspark/flexboxfroggy#202]

**Comment by obadakhalili** [comment]
I've tried to delete all of the site storage, but nothing seems to work.

**Comment by minna-xD** [comment]
The reset button under the level menu doesn't work? (click on "Level x of 24" and then "Reset" at the bottom)

**Comment by obadakhalili** [comment]
It does work, I just didn't know it exists 😅. Maybe it has to do with the fact that it's so well-hidden, nevertheless, I should have looked better. Thanks!

Although I have to ask how did you manage to retrieve the solved levels even after the entire storage of the site is removed?

**Comment by thanhkhanhcntt** [comment]
> The reset button under the level menu doesn't work? (click on "Level x of 24" and then "Reset" at the bottom) (Sorry if that's a stupid question...)

I have the same question, so you do not stupid. The UX stupid. It should move the reset button to front out.
