### ISSUE TITLE
Hovering on level reveals some information about how to approach the level

### ISSUE THREAD

**Issue by shishir610** [thomaspark/flexboxfroggy#213]
**Description:**
While hovering on any level, some information such as `align-item` or `justify-content` is revealed which compromises the need to have intermediate and expert difficulties

![FlexboxFroggy1](https://user-images.githubusercontent.com/27198773/118636429-515dc300-b7f2-11eb-96fa-84c4d57a587c.png)

**Steps to recreate issue:**
1. Go to https://flexboxfroggy.com/
2. Click on the Levels dropdown 
3. Hover on any level

**Ideal behaviour:**
We should not display anything after hovering the level button.

**Comment by thomaspark** [comment]
@shishir610, thanks for the issue. We'll hide the level tooltips at intermediate and expert difficulty.
