### ISSUE TITLE
Level 24 issue solution request.

### ISSUE THREAD

**Issue by Alwaysherewithme** [thomaspark/flexboxfroggy#215]
Hi, I've tried solved the level 24 but failed several times, I'm afraid that it couldn't be achieved using only one CSS selector. Could the right solution be shared? Thanks for creating the game!

**Comment by thomaspark** [comment]
Hey @Alwaysherewithme, check out #21 for a discussion on it!

**Comment by Alwaysherewithme** [comment]
> Hey @Alwaysherewithme, check out #21 for a discussion on it!

Great helps! Thanks Thomas.
