### ISSUE TITLE
Use SVG for icons?

### ISSUE THREAD

**Issue by tabatkins** [thomaspark/flexboxfroggy#22]
The froggies are a bit fuzzy on my monitor, since they're PNGs.  These little buddies are perfect for SVG, composed of simple shapes and flat colors.  It'll make the filesize a little smaller, too.

**Comment by thomaspark** [comment]
Thanks for the suggestion, there was similar discussion also in #14.

I'm making the switch from png to svg. The image load drops from 49kb to 25kb and as for image quality, you can judge for yourself. PNG left, SVG right.

<img width="162" alt="screen shot 2015-12-05 at 3 37 01 am" src="https://cloud.githubusercontent.com/assets/900407/11606940/01fae954-9b02-11e5-87b2-9aa2ef20095d.png"> <img width="162" alt="screen shot 2015-12-05 at 3 36 54 am" src="https://cloud.githubusercontent.com/assets/900407/11606941/0553dca0-9b02-11e5-9f68-4bc0a967e43c.png">

**Comment by tabatkins** [comment]
:+1:
