### ISSUE TITLE
twttr is not defined error

### ISSUE THREAD

**Issue by qowlz** [thomaspark/flexboxfroggy#226]
![image](https://user-images.githubusercontent.com/33592844/142585952-8721ba3d-dd58-4d0a-a515-420b7b569d03.png)
When I open first flexfloggy.com with chrome app, twtrr error occured as above. 
I'm guessing [this error](https://stackoverflow.com/questions/49635537/referenceerror-twttr-is-not-defined).
Error occur steps are as follows.
1. Open chrome app
2. Enter "flexboxfroggy.com" and connect to site
3. open developer tool(F12) and check above error log

my language setting is korean. 
please check this error!

**Comment by thomaspark** [comment]
Thanks for the bug report. I'm not able to replicate this, maybe an ad blocker is blocking the Twitter script for you. In any case, I'll add a check for `twttr`.

**Comment by qowlz** [comment]
Hello @thomaspark Sorry for late reply. 
I checked your uploaded code! 
The above error no longer occurs in my environment. Thank you for quick fix. I'll close this issue.
