### ISSUE TITLE
Hovering over text doesn't give hints, but clicking does

### ISSUE THREAD

**Issue by hamirmahal** [thomaspark/flexboxfroggy#237]
This is in Microsoft Edge on Windows 10.

https://user-images.githubusercontent.com/43425812/192708136-22c885de-f794-4fe4-9f33-ff349a4ecc46.mp4

**Comment by thomaspark** [comment]
Hey @hamirmahal, the instructions are outdated here and should be updated. We changed from hover to click for hints a little while back.
