### ISSUE TITLE
[Typo] Is this typo or somekind of pun I'm not getting !?

### ISSUE THREAD

**Issue by arshit09** [thomaspark/flexboxfroggy#246]
![image](https://user-images.githubusercontent.com/31356599/232631574-1aaaab4b-de80-4078-9e30-a371aac68ee8.png)

**Comment by minna-xD** [comment]
It's a pun. Frogs hop (jump), they are "hoppy". 

Question has been asked and answered before, e.g. 
https://github.com/thomaspark/flexboxfroggy/issues/167

**Comment by arshit09** [comment]
Got it! Thanks.

**Comment by arshit09** [comment]
Got it! Thanks
