### ISSUE TITLE
Azerbaijan language

### ISSUE THREAD

**Issue by jalalbmnf** [thomaspark/flexboxfroggy#248]
Hello. I want to add Azerbaijan language for this project :)

**Comment by thomaspark** [comment]
Translation would also be welcome for Froggy!

**Comment by jalalbmnf** [comment]
I will work on this too

**Comment by jalalbmnf** [comment]
#249 Ready :)

**Comment by thomaspark** [comment]
Looks good, thanks @jalalbmnf!

**Comment by thomaspark** [comment]
Merged in #249.
