### ISSUE TITLE
Additional Portuguese translations

### ISSUE THREAD

**Issue by thomaspark** [thomaspark/flexboxfroggy#25]
There are a few new Portuguese translations left to do.

In https://github.com/thomaspark/flexboxfroggy/blob/gh-pages/js/messages.js:
* "Reset"
* "Are you sure you want to reset the game?\n\nYour saved progress will be lost and you\'ll be sent to the start of the game."

@mvtenorio, mind helping out with these? :smile:

**Comment by mvtenorio** [comment]
Done! :smile:

**Comment by thomaspark** [comment]
Thank you!
