### ISSUE TITLE
Clicking on the links provided lets users add extra lines

### ISSUE THREAD

**Issue by Oran** [thomaspark/flexboxfroggy#273]
Not sure if this is a **bug** or an indented feature

![image](https://github.com/thomaspark/flexboxfroggy/assets/42975732/3748c8ee-5603-4c92-927b-3e3982943e82)

In the example above you can click on the links provided and it adds another line. To me this looks like a bug and not an intended use case.

This can be replicated in every problems that have multiple properties.

![image](https://github.com/thomaspark/flexboxfroggy/assets/42975732/c591aed2-28af-47bc-8311-db6a0c49a597)

**Comment by thomaspark** [comment]
Hi, this is an intended feature.
