### ISSUE TITLE
Level 14

### ISSUE THREAD

**Issue by xDiglett** [thomaspark/flexboxfroggy#3]
So I assume 1 is the correct answer for the order, however entering 2 or 3 works too?

**Comment by thomaspark** [comment]
It works like `z-index` in that if the value is greater than the value of the others (in this case, the default 0), it'll be moved to the end of the order. So 1, 2, 3,... are all valid answers.

**Comment by xDiglett** [comment]
oh I see, thanks!

**Comment by thomaspark** [comment]
No problem!
