### ISSUE TITLE
Harder mode

### ISSUE THREAD

**Issue by HugoHeneault** [thomaspark/flexboxfroggy#35]
Awesome game. Perfect for checking our skills. :+1: 

An harder mode, without saying which properties should be used would be great!

**Comment by thomaspark** [comment]
How does something like #27 sound? Repeating the levels with the instructions toggled off.

I was also thinking about a mode that generates levels with a random combination of properties.

**Comment by HugoHeneault** [comment]
This would be great! That's what I was thinking.

**Comment by rachelreveley** [comment]
I found the first 26 steps really easy but then was stumped for about 10 minutes on 27. Maybe some steps in between would be great.

Brilliant job though.

**Comment by mcshiz** [comment]
created a pull request for a "hard mode" https://github.com/thomaspark/flexboxfroggy/pull/127
