### ISSUE TITLE
Do not remove documentation about properties and values from last level.

### ISSUE THREAD

**Issue by vsviridov** [thomaspark/flexboxfroggy#5]
I think it's unreasonable to expect anyone to memorize all of the properties and their values in time it takes to go through first 23 steps.

It ends up being quite frustrating to break one's train of thought and state because one has to go back and look up property or value one might try.

**Comment by naeemnur** [comment]
+1

**Comment by andreas-becker** [comment]
+1

**Comment by thomaspark** [comment]
I intended for the last level to be like a video game boss fight, so it is meant to be tougher than the others for sure.

But that doesn't mean I expect people to memorize all of the properties and values. I actually added a few features (which might not all be obvious) to encourage people to flip back and forth to earlier lessons as reference:

* You can hit the back and prev level buttons

* Your state is saved whenever you move to a different level

* You can hover any property name to view a tooltip reference

    <img width="274" alt="screen shot 2015-12-01 at 3 14 55 pm" src="https://cloud.githubusercontent.com/assets/900407/11512860/4d23be9a-983e-11e5-9289-49f331d42ba9.png">

* You can click "Level n of 24" to jump directly to any level and see their completion state

    <img width="286" alt="screen shot 2015-12-01 at 3 14 06 pm" src="https://cloud.githubusercontent.com/assets/900407/11512868/56f14b72-983e-11e5-9ee9-c7762fe45777.png">

I only did this at the end so it doesn't break the flow. My hope is the last level gives players a real sense of accomplishment for beating the game.

**Comment by vsviridov** [comment]
Game state is retained, but the mental state is not... Every time i switch away I'd have to remember what it is that I'm trying to do, and since most properties are scattered across levels, and there's no clear indication which level has which property it turns into an unnecessary hunt.

Learning is not supposed to be frustrating, this is not high school :D

**Comment by thomaspark** [comment]
That's fair enough. Listing all of the properties in the final level text would definitely reduce frustration, and should keep much of the challenge.

**Comment by amfarrell** [comment]
I wonder if having the properties not initially shown, but showable, is a better idea. Part of what I've been looking for in a tutorial is having to memorize the names and effects of properties.

As an aside: can I just say that I *really* *really* like this tutorial?

**Comment by d48** [comment]
I suggest just making a legend that shows somewhere after the property has been introduced and user can see values. I had to look this up by going back a few levels after I got to level 24. The legend for quick lookup would be really helpful

**Comment by RubenSandwich** [comment]
I agree with @d48. Having some sort of reference that is there only if the learner needs it would be helpful. I think a popover reference would be better then a tooltip reference, as it requires more a little more work for the learner to view it and thus would encourage them not to overuse it.

**Comment by n1k0** [comment]
+1, for a newcomer like me that last level is a pain, having to go back through all different levels to access the docs. 

Sure, people could search for these docs elsewhere on the Web, but people are lazy, and it's sad loosing them because of that.

> Game state is retained, but the mental state is not

This so much.

**Comment by brianzelip** [comment]
I appreciated the boss fight ending of the last level. It was a real challenge. Great game!

**Comment by cecyc** [comment]
Might be in the minority, but I actually liked this because it got me to go to MDN and look up the properties, like I would have in real life :)

https://developer.mozilla.org/en-US/docs/Web/CSS/flex-flow
https://developer.mozilla.org/en-US/docs/Web/CSS/flex-wrap

Maybe add a link to look up documentation instead?

**Comment by ckedwards** [comment]
+1 to @cecyc 

It is always valuable to make sure new devs know about MDN. w3schools be damned!
