### ISSUE TITLE
Make <div class="button"> a <button>

### ISSUE THREAD

**Issue by AmeliaBR** [thomaspark/flexboxfroggy#50]
The "Next" button-like-div which must be activated after completing a level cannot be reached by keyboard. Easiest and most comprehensive fix is to make it (and all other `<div class="button">`) into a proper `<button>`.

**Comment by thomaspark** [comment]
You should be able to just hit "enter" to submit your answer, but making it more semantic and accessible doesn't hurt. Pushing a change for this now. Thanks for the suggestion.

**Comment by AmeliaBR** [comment]
Great! I'm not sure why I didn't try "enter", probably because I wasn't expecting it to work in a multi-line text field, but either way `button` is a wonderful element for many reasons.
