### ISSUE TITLE
Wrong Language Displayed

### ISSUE THREAD

**Issue by dk0r** [thomaspark/flexboxfroggy#59]
**Issue**: Both level 18 and 20 automatically switches to some non-English language even after English is selected from the bottom of the page.

**Reproduce**: 1) Visit flexboxfroggy.com/#en  2) Complete levels up to 17  3) Notice that lvl-18 automatically switches to a non-English language. _Note_: Proceeding to lvl-19 automatically restores the language back to English.
 
**Screenshot**: http://i.imgur.com/0DSWfep.png

**Comment by devrelm** [comment]
Submitted pull request #60 to fix this.
