### ISSUE TITLE
Level 15 puts red frog at the end

### ISSUE THREAD

**Issue by knod** [thomaspark/flexboxfroggy#65]
In level 15, if I use any non-zero integer after `order:`, such as `order: 1;`, the red frog goes to the right-most spot, while the lily pad stays to the very left. If I use `order: 0;`, of course, it stays in the same place, second from the right.

Macbook Pro, v 10.11, Chrome v 48.0.2564.109

**Comment by knod** [comment]
Never mind, I didn't realize `order` could take negative values.

**Comment by thomaspark** [comment]
Ok, will close this issue. Cheers.
