### ISSUE TITLE
Unexpected language change from English to Hungarian

### ISSUE THREAD

**Issue by dm-wyncode** [thomaspark/flexboxfroggy#71]
I am a student at [Wyncode Academy](https://wyncode.co/).

Our instructor [Auston Busen](https://github.com/abunsen) suggested your awesome game as a way to learn Flexbox.

At level 14, I answered correctly and pressed "next".

The language changed to Hungarian as [described here](https://slack-files.com/T055GEHEJ-F1367HS3B-15939bf286).

I answered correctly and pressed "next" again. The language remained in Hungarian.

I pressed the "English" link at the bottom. Still Hungarian. I pressed the "French" link,  and the language changed to French. I manually entered `http://flexboxfroggy.com/#en` into Chrome's location and still the language was Hungarian.

I finally tried pressing "Magyar" and then "English" and the language was then in English.

Thanks for making Flexbox Froggy!

**Comment by thomaspark** [comment]
Hi @dm-wyncode, the Hungarian translation was recently added. A bug is causing the new Hungarian instructions to overwrite English for levels 14 and 15. Thanks for your detailed report — I was able to track it down and will push a fix shortly.
