### ISSUE TITLE
Does it work on Firefox ?

### ISSUE THREAD

**Issue by siemiatj** [thomaspark/flexboxfroggy#74]
Maybe it's some 3rd party lib, or a plugin in my browser but it seems to be broken on Fx. Using 46.0.1.

![screen shot 2016-05-25 at 10 14 23 pm](https://cloud.githubusercontent.com/assets/513460/15564373/5dd0d1a2-22c6-11e6-9f93-c503082e8e3f.png)

**Comment by thomaspark** [comment]
Works ok for me on Firefox 46.0.1. Are you seeing any errors in console?

**Comment by HoBi** [comment]
Works well for me on Firefox 46.0.1 / Windows 10.

**Comment by martinkrulltott** [comment]
Works on Firefox 46.0.1 on Mac OSX (10.11.3) as well.
