### ISSUE TITLE
Level 14: explain integer

### ISSUE THREAD

**Issue by DanielMSchmidt** [thomaspark/flexboxfroggy#79]
Hi there,

First of all big thanks for this great project, it helped me and a lot of people I know.
For example, my girlfriend who is currently learning HTML and CSS with no computer science or programming background at all. This is the problem I would like to discuss, in level 14 the term "Integer" is used, probably because we engineers tend to not think too much about it. I would love to see a little explanation added for what integer means in this overlay.

If it is in your interest I would add a PR for this.

Have a nice day and thanks again for this great project!

**Comment by thomaspark** [comment]
Thanks for the suggestion, I'd be open to a PR for this. Maybe something as simple as a parenthetical with example numbers would be enough. This would be easy to add to all translations as well.

Something like:
> ...we can use this property to set it to a positive or negative integer value. (...-2, -1, 0, 1, 2,...)

**Comment by snan** [comment]
Yeah, word "integer" is the problem, please add something like "a number without any decimals" or w/e.

**Comment by snan** [comment]
The `<datatype>` bracket example formatting is also not intuitively clear to new programmers who aren't used to metasyntactic variables and casting.
