### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by manuelitox** [thomaspark/flexboxfroggy#8]
Hi Thomas,

Flexbox Froggy is insane, it's really good. I'd like to help with the Spanish translation, Do you think it's possible?

**Comment by thomaspark** [comment]
Would love your help in localizing this! I'll look into getting Froggy set up for localization, so you can drop in the translations. If you know any libraries that would help with this, please let me know.

**Comment by thomaspark** [comment]
Hey @manuelitox, Flexbox Froggy is ready for translation! They can be added to the following files by including an `es` property beside the `en` one. I've already added a couple of test cases (using Google Translate).

* `js/levels.js`
* `js/docs.js`

There are also a few strings that should be translated in `lang/es/index.html` such as "Level" and "Next".

The Spanish version will be available at http://flexboxfroggy.com/lang/es/. Look forward to your translations! Once it's ready, I'll add a link to the main page.

**Comment by mvtenorio** [comment]
Nice! I can help with the Brazilian Portuguese translation. :smile:

**Comment by manuelitox** [comment]
@thomaspark sounds good!

Soon I'll start the translations.

**Comment by thomaspark** [comment]
@mvtenorio, would be great to also have a Portuguese translation. Let me know if you have any questions about how to add it to the project.

@manuelitox, awesome!

**Comment by thomaspark** [comment]
Added in c991397bc5169cc263faaddde41976c5744ea964!
