### ISSUE TITLE
[Suggestion] Color-deficient mode

### ISSUE THREAD

**Issue by Aydee221** [thomaspark/flexboxfroggy#81]
Can you make a color-blind / color-deficient mode? It's extremely difficult for some people to see the difference between the red and green frogs and lilly pads. 

Thanks for considering! Excellent learning resources.

**Comment by thomaspark** [comment]
I would definitely be open to something this. Maybe an alternate color palette, or giving the frogs different patterns. Other ideas?

**Comment by Agentscreech** [comment]
Just change the green frog and target pad to blue.  That will fix the most common color-blindness (red-green)  Then you can keep adding incremental schemes for the other forms

**Comment by Balance-Breaker** [comment]
Just a suggestion:
To write a number in the on the frogs stomach and on the corresponding leaf if not the change of color.
