### ISSUE TITLE
Identify 'stretch' as the default.

### ISSUE THREAD

**Issue by mrchess** [thomaspark/flexboxfroggy#92]
For things like `align-content`, there is no mention that `stretch` is the default. It would be nice to add on the attribute descriptions that `stretch` is default.

**Comment by participator** [comment]
I would like to add this.  Adding an asterisk or '(default)' for the default values of all properties should address this concern.

**Comment by thomaspark** [comment]
Thanks for the good suggestion. This feature has been added!

<img width="666" alt="Screen Shot 2019-11-07 at 5 20 50 PM" src="https://user-images.githubusercontent.com/900407/68432712-fcfc7080-0182-11ea-93e6-ee87bcdf8cfd.png">

**Comment by participator** [comment]
Looks nice.  However, I was hoping to contribute by implementing it.  Any other features that I could implement?

**Comment by thomaspark** [comment]
Sure, contributions are very welcome.

How about adding browser support info (#121) to this repo's readme like in [thomaspark/gridgarden](https://github.com/thomaspark/gridgarden)?

A feature like #131 would be a nice enhancement too.

**Comment by participator** [comment]
Cool, thanks for the suggestions.  I'll try #121 as I don't necessarily like #131.  Is there a recommended way to test for browser support?

**Comment by thomaspark** [comment]
[Can I Use](https://caniuse.com/#feat=flexbox) is a great resource for that.

**Comment by qowlz** [comment]
thanks! I will start task right now :)
