### ISSUE TITLE
Amazing! This project must be adapted for grid layouts too!

### ISSUE THREAD

**Issue by pribilinskiy** [thomaspark/flexboxfroggy#97]
Learning (and recalling) flexbox layout properties with Flexbox Froggy is fun!

Now grid layout is here!
http://caniuse.com/#search=grid
https://css-tricks.com/snippets/css/complete-guide-grid/

And it is already can be used with `@supports (display: grid) {}`

It would be great to adapt **Froggy** to the new css layout module or make a new project, e.g. **Grid Giraffe** with variable neck sizes!

**Comment by thomaspark** [comment]
![gridgarden](https://cloud.githubusercontent.com/assets/900407/24732242/b0689f02-1a3d-11e7-8168-8fb4a4d48951.png)

Just put the finishing touches on Grid Garden:

http://cssgridgarden.com/
https://github.com/thomaspark/gridgarden

Loved the Grid Giraffe idea but sadly couldn't get it to work. 😛

**Comment by pribilinskiy** [comment]
Wow, just wow, great work!
The garden theme is suited even more )
Thanks!

**Comment by thomaspark** [comment]
Turns out a carrot is much easier to draw than a giraffe!
